// Bibliothèque d'exercices intégrée
// unit — type de compteur pour la saisie des séries :
//   "kg"  : charge (kg) × répétitions
//   "pdc" : poids de corps — répétitions + lest optionnel (kg)
//   "min" : durée en minutes, avec chronomètre intégré
export const EXERCISE_LIBRARY = [
  // Pectoraux
  { id: "dev-couche", name: "Développé couché", group: "Pectoraux", unit: "kg" },
  { id: "dev-couche-halteres", name: "Développé couché haltères", group: "Pectoraux", unit: "kg" },
  { id: "dev-incline", name: "Développé incliné", group: "Pectoraux", unit: "kg" },
  { id: "dev-incline-halteres", name: "Développé incliné haltères", group: "Pectoraux", unit: "kg" },
  { id: "ecarte-halteres", name: "Écarté haltères", group: "Pectoraux", unit: "kg" },
  { id: "ecarte-poulie", name: "Écarté à la poulie", group: "Pectoraux", unit: "kg" },
  { id: "pompes", name: "Pompes", group: "Pectoraux", unit: "pdc" },
  { id: "dips", name: "Dips", group: "Pectoraux", unit: "pdc" },

  // Dos
  { id: "tractions", name: "Tractions", group: "Dos", unit: "pdc" },
  { id: "tirage-vertical", name: "Tirage vertical", group: "Dos", unit: "kg" },
  { id: "rowing-barre", name: "Rowing barre", group: "Dos", unit: "kg" },
  { id: "rowing-haltere", name: "Rowing haltère", group: "Dos", unit: "kg" },
  { id: "tirage-horizontal", name: "Tirage horizontal", group: "Dos", unit: "kg" },
  { id: "souleve-de-terre", name: "Soulevé de terre", group: "Dos", unit: "kg" },
  { id: "pull-over", name: "Pull-over", group: "Dos", unit: "kg" },

  // Épaules
  { id: "dev-militaire", name: "Développé militaire", group: "Épaules", unit: "kg" },
  { id: "dev-halteres-assis", name: "Développé haltères assis", group: "Épaules", unit: "kg" },
  { id: "elevations-laterales", name: "Élévations latérales", group: "Épaules", unit: "kg" },
  { id: "elevations-frontales", name: "Élévations frontales", group: "Épaules", unit: "kg" },
  { id: "oiseau", name: "Oiseau (élévations buste penché)", group: "Épaules", unit: "kg" },
  { id: "face-pull", name: "Face pull", group: "Épaules", unit: "kg" },
  { id: "shrugs", name: "Shrugs", group: "Épaules", unit: "kg" },

  // Biceps
  { id: "curl-barre", name: "Curl barre", group: "Biceps", unit: "kg" },
  { id: "curl-halteres", name: "Curl haltères", group: "Biceps", unit: "kg" },
  { id: "curl-marteau", name: "Curl marteau", group: "Biceps", unit: "kg" },
  { id: "curl-incline", name: "Curl incliné", group: "Biceps", unit: "kg" },
  { id: "curl-pupitre", name: "Curl pupitre (Larry Scott)", group: "Biceps", unit: "kg" },

  // Triceps
  { id: "extension-poulie", name: "Extension triceps poulie", group: "Triceps", unit: "kg" },
  { id: "barre-au-front", name: "Barre au front", group: "Triceps", unit: "kg" },
  { id: "extension-nuque", name: "Extension nuque haltère", group: "Triceps", unit: "kg" },
  { id: "dips-triceps", name: "Dips prise serrée", group: "Triceps", unit: "pdc" },
  { id: "kickback", name: "Kickback triceps", group: "Triceps", unit: "kg" },

  // Jambes
  { id: "squat", name: "Squat", group: "Jambes", unit: "kg" },
  { id: "front-squat", name: "Front squat", group: "Jambes", unit: "kg" },
  { id: "presse", name: "Presse à cuisses", group: "Jambes", unit: "kg" },
  { id: "fentes", name: "Fentes", group: "Jambes", unit: "kg" },
  { id: "leg-extension", name: "Leg extension", group: "Jambes", unit: "kg" },
  { id: "leg-curl", name: "Leg curl", group: "Jambes", unit: "kg" },
  { id: "mollets-debout", name: "Mollets debout", group: "Jambes", unit: "kg" },
  { id: "souleve-terre-roumain", name: "Soulevé de terre roumain", group: "Jambes", unit: "kg" },

  // Fessiers
  { id: "hip-thrust", name: "Hip thrust", group: "Fessiers", unit: "kg" },
  { id: "pont-fessier", name: "Pont fessier", group: "Fessiers", unit: "kg" },
  { id: "abduction-machine", name: "Abduction machine", group: "Fessiers", unit: "kg" },

  // Abdos
  { id: "crunch", name: "Crunch", group: "Abdos", unit: "pdc" },
  { id: "releve-jambes", name: "Relevé de jambes", group: "Abdos", unit: "pdc" },
  { id: "planche", name: "Planche (gainage)", group: "Abdos", unit: "min" },
  { id: "russian-twist", name: "Russian twist", group: "Abdos", unit: "pdc" },
  { id: "roulette-abdos", name: "Roulette abdominale", group: "Abdos", unit: "kg" },

  // Cardio
  { id: "course", name: "Course à pied", group: "Cardio", unit: "min" },
  { id: "velo", name: "Vélo", group: "Cardio", unit: "min" },
  { id: "rameur", name: "Rameur", group: "Cardio", unit: "min" },
  { id: "corde-a-sauter", name: "Corde à sauter", group: "Cardio", unit: "min" },
  { id: "marche-inclinee", name: "Marche inclinée", group: "Cardio", unit: "min" },
];

export const EXERCISE_GROUPS = ["Pectoraux", "Dos", "Épaules", "Biceps", "Triceps", "Jambes", "Fessiers", "Abdos", "Cardio"];

/* =========================================================
   Bibliothèque d'aliments intégrée (~300 produits)
   Valeurs moyennes pour 100 g (100 ml pour les boissons),
   sources type Ciqual/ANSES. kcal, prot (g), gluc (g), lip (g).
   ========================================================= */
export const FOOD_LIBRARY = [
  /* ---------- Viandes & charcuterie ---------- */
  { id: "poulet", name: "Blanc de poulet", cat: "Viandes", kcal: 120, prot: 26, gluc: 0, lip: 1.5 },
  { id: "poulet-cuisse", name: "Cuisse de poulet (sans peau)", cat: "Viandes", kcal: 170, prot: 21, gluc: 0, lip: 9 },
  { id: "poulet-roti", name: "Poulet rôti (avec peau)", cat: "Viandes", kcal: 220, prot: 27, gluc: 0, lip: 12 },
  { id: "dinde", name: "Escalope de dinde", cat: "Viandes", kcal: 110, prot: 24, gluc: 0, lip: 1 },
  { id: "dinde-tranches", name: "Blanc de dinde (tranches)", cat: "Viandes", kcal: 105, prot: 22, gluc: 1, lip: 1 },
  { id: "boeuf-5", name: "Steak haché 5%", cat: "Viandes", kcal: 137, prot: 21, gluc: 0, lip: 5 },
  { id: "boeuf-15", name: "Steak haché 15%", cat: "Viandes", kcal: 215, prot: 18, gluc: 0, lip: 15 },
  { id: "entrecote", name: "Entrecôte grillée", cat: "Viandes", kcal: 270, prot: 25, gluc: 0, lip: 19 },
  { id: "filet-boeuf", name: "Filet de bœuf", cat: "Viandes", kcal: 150, prot: 21, gluc: 0, lip: 7 },
  { id: "filet-mignon-porc", name: "Filet mignon de porc", cat: "Viandes", kcal: 120, prot: 21, gluc: 0, lip: 3.5 },
  { id: "cote-porc", name: "Côte de porc", cat: "Viandes", kcal: 250, prot: 25, gluc: 0, lip: 16 },
  { id: "escalope-veau", name: "Escalope de veau", cat: "Viandes", kcal: 110, prot: 22, gluc: 0, lip: 2.5 },
  { id: "gigot-agneau", name: "Gigot d'agneau", cat: "Viandes", kcal: 220, prot: 25, gluc: 0, lip: 13 },
  { id: "magret-canard", name: "Magret de canard (sans peau)", cat: "Viandes", kcal: 190, prot: 24, gluc: 0, lip: 10 },
  { id: "lapin", name: "Lapin", cat: "Viandes", kcal: 140, prot: 21, gluc: 0, lip: 6 },
  { id: "foie-volaille", name: "Foie de volaille", cat: "Viandes", kcal: 135, prot: 20, gluc: 4, lip: 4 },
  { id: "jambon", name: "Jambon blanc", cat: "Viandes", kcal: 115, prot: 21, gluc: 1, lip: 3 },
  { id: "jambon-cru", name: "Jambon cru", cat: "Viandes", kcal: 230, prot: 26, gluc: 0, lip: 14 },
  { id: "viande-grisons", name: "Viande des Grisons", cat: "Viandes", kcal: 195, prot: 38, gluc: 1, lip: 4 },
  { id: "bacon", name: "Bacon fumé", cat: "Viandes", kcal: 145, prot: 20, gluc: 0.5, lip: 7 },
  { id: "lardons", name: "Lardons", cat: "Viandes", kcal: 290, prot: 14, gluc: 0.5, lip: 26 },
  { id: "saucisse-toulouse", name: "Saucisse de Toulouse", cat: "Viandes", kcal: 320, prot: 15, gluc: 1, lip: 29 },
  { id: "chipolata", name: "Chipolata", cat: "Viandes", kcal: 300, prot: 15, gluc: 1, lip: 27 },
  { id: "merguez", name: "Merguez", cat: "Viandes", kcal: 300, prot: 15, gluc: 1, lip: 26 },
  { id: "chorizo", name: "Chorizo", cat: "Viandes", kcal: 455, prot: 24, gluc: 2, lip: 38 },
  { id: "saucisson", name: "Saucisson sec", cat: "Viandes", kcal: 415, prot: 26, gluc: 2, lip: 34 },
  { id: "pate-campagne", name: "Pâté de campagne", cat: "Viandes", kcal: 320, prot: 14, gluc: 2, lip: 28 },
  { id: "boudin-noir", name: "Boudin noir", cat: "Viandes", kcal: 300, prot: 11, gluc: 4, lip: 27 },

  /* ---------- Poissons & fruits de mer ---------- */
  { id: "saumon", name: "Saumon", cat: "Poissons & mer", kcal: 200, prot: 20, gluc: 0, lip: 13 },
  { id: "saumon-fume", name: "Saumon fumé", cat: "Poissons & mer", kcal: 180, prot: 23, gluc: 0, lip: 10 },
  { id: "thon", name: "Thon au naturel (boîte)", cat: "Poissons & mer", kcal: 110, prot: 25, gluc: 0, lip: 1 },
  { id: "thon-frais", name: "Thon frais", cat: "Poissons & mer", kcal: 140, prot: 24, gluc: 0, lip: 5 },
  { id: "cabillaud", name: "Cabillaud", cat: "Poissons & mer", kcal: 82, prot: 18, gluc: 0, lip: 0.7 },
  { id: "colin", name: "Colin / lieu", cat: "Poissons & mer", kcal: 80, prot: 18, gluc: 0, lip: 0.8 },
  { id: "merlu", name: "Merlu", cat: "Poissons & mer", kcal: 85, prot: 17, gluc: 0, lip: 2 },
  { id: "dorade", name: "Dorade", cat: "Poissons & mer", kcal: 100, prot: 20, gluc: 0, lip: 2.5 },
  { id: "bar", name: "Bar / loup", cat: "Poissons & mer", kcal: 100, prot: 19, gluc: 0, lip: 2.5 },
  { id: "truite", name: "Truite", cat: "Poissons & mer", kcal: 120, prot: 20, gluc: 0, lip: 4.5 },
  { id: "sardines", name: "Sardines à l'huile (égouttées)", cat: "Poissons & mer", kcal: 210, prot: 24, gluc: 0, lip: 13 },
  { id: "maquereau", name: "Maquereau", cat: "Poissons & mer", kcal: 240, prot: 20, gluc: 0, lip: 18 },
  { id: "hareng-fume", name: "Hareng fumé", cat: "Poissons & mer", kcal: 215, prot: 20, gluc: 0, lip: 15 },
  { id: "anchois", name: "Anchois à l'huile", cat: "Poissons & mer", kcal: 210, prot: 25, gluc: 0, lip: 12 },
  { id: "poisson-pane", name: "Poisson pané", cat: "Poissons & mer", kcal: 200, prot: 12, gluc: 18, lip: 9 },
  { id: "crevettes", name: "Crevettes", cat: "Poissons & mer", kcal: 100, prot: 21, gluc: 1, lip: 1 },
  { id: "moules", name: "Moules", cat: "Poissons & mer", kcal: 90, prot: 12, gluc: 3.5, lip: 2.2 },
  { id: "calamars", name: "Calamars", cat: "Poissons & mer", kcal: 82, prot: 15.5, gluc: 1.5, lip: 1.2 },
  { id: "st-jacques", name: "Noix de Saint-Jacques", cat: "Poissons & mer", kcal: 90, prot: 17, gluc: 2, lip: 1 },
  { id: "huitres", name: "Huîtres", cat: "Poissons & mer", kcal: 66, prot: 9, gluc: 4, lip: 1.7 },
  { id: "surimi", name: "Surimi", cat: "Poissons & mer", kcal: 95, prot: 8, gluc: 11, lip: 2.5 },

  /* ---------- Œufs & protéines végétales ---------- */
  { id: "oeuf", name: "Œuf entier", cat: "Œufs & végétal", kcal: 145, prot: 12.5, gluc: 0.7, lip: 10 },
  { id: "blanc-oeuf", name: "Blanc d'œuf", cat: "Œufs & végétal", kcal: 47, prot: 10.5, gluc: 0.7, lip: 0.2 },
  { id: "jaune-oeuf", name: "Jaune d'œuf", cat: "Œufs & végétal", kcal: 320, prot: 16, gluc: 1, lip: 28 },
  { id: "omelette", name: "Omelette nature", cat: "Œufs & végétal", kcal: 155, prot: 11, gluc: 1, lip: 12 },
  { id: "tofu", name: "Tofu nature", cat: "Œufs & végétal", kcal: 118, prot: 12, gluc: 1.5, lip: 7 },
  { id: "tofu-fume", name: "Tofu fumé", cat: "Œufs & végétal", kcal: 150, prot: 16, gluc: 1, lip: 9 },
  { id: "tempeh", name: "Tempeh", cat: "Œufs & végétal", kcal: 190, prot: 19, gluc: 9, lip: 9 },
  { id: "seitan", name: "Seitan", cat: "Œufs & végétal", kcal: 130, prot: 24, gluc: 5, lip: 1.5 },
  { id: "proteines-soja", name: "Protéines de soja texturées", cat: "Œufs & végétal", kcal: 345, prot: 50, gluc: 24, lip: 4 },
  { id: "steak-soja", name: "Steak de soja", cat: "Œufs & végétal", kcal: 190, prot: 17, gluc: 8, lip: 10 },
  { id: "falafel", name: "Falafels", cat: "Œufs & végétal", kcal: 330, prot: 13, gluc: 30, lip: 17 },

  /* ---------- Féculents & légumineuses ---------- */
  { id: "riz-cuit", name: "Riz blanc cuit", cat: "Féculents", kcal: 130, prot: 2.7, gluc: 28, lip: 0.3 },
  { id: "riz-complet-cuit", name: "Riz complet cuit", cat: "Féculents", kcal: 122, prot: 2.7, gluc: 25, lip: 1 },
  { id: "riz-basmati", name: "Riz basmati cuit", cat: "Féculents", kcal: 135, prot: 3, gluc: 29, lip: 0.4 },
  { id: "pates-cuites", name: "Pâtes cuites", cat: "Féculents", kcal: 155, prot: 5.5, gluc: 30, lip: 0.9 },
  { id: "pates-completes", name: "Pâtes complètes cuites", cat: "Féculents", kcal: 132, prot: 5.3, gluc: 26, lip: 1.2 },
  { id: "semoule", name: "Semoule cuite", cat: "Féculents", kcal: 150, prot: 5, gluc: 30, lip: 0.5 },
  { id: "boulgour", name: "Boulgour cuit", cat: "Féculents", kcal: 118, prot: 4, gluc: 23, lip: 0.4 },
  { id: "quinoa-cuit", name: "Quinoa cuit", cat: "Féculents", kcal: 120, prot: 4.4, gluc: 21, lip: 1.9 },
  { id: "ble-cuit", name: "Blé cuit (type Ebly)", cat: "Féculents", kcal: 130, prot: 4.5, gluc: 26, lip: 0.6 },
  { id: "polenta", name: "Polenta cuite", cat: "Féculents", kcal: 85, prot: 2, gluc: 17, lip: 0.5 },
  { id: "gnocchis", name: "Gnocchis", cat: "Féculents", kcal: 165, prot: 4, gluc: 33, lip: 1 },
  { id: "vermicelles-riz", name: "Vermicelles de riz cuits", cat: "Féculents", kcal: 110, prot: 1.5, gluc: 25, lip: 0.2 },
  { id: "pdt", name: "Pomme de terre (vapeur)", cat: "Féculents", kcal: 86, prot: 2, gluc: 19, lip: 0.1 },
  { id: "puree", name: "Purée de pommes de terre", cat: "Féculents", kcal: 100, prot: 2, gluc: 14, lip: 3.5 },
  { id: "frites", name: "Frites", cat: "Féculents", kcal: 290, prot: 3.4, gluc: 36, lip: 14 },
  { id: "patate-douce", name: "Patate douce", cat: "Féculents", kcal: 86, prot: 1.6, gluc: 20, lip: 0.1 },
  { id: "flocons-avoine", name: "Flocons d'avoine", cat: "Féculents", kcal: 370, prot: 13, gluc: 60, lip: 7 },
  { id: "muesli", name: "Muesli", cat: "Féculents", kcal: 360, prot: 9, gluc: 60, lip: 8 },
  { id: "granola", name: "Granola", cat: "Féculents", kcal: 450, prot: 9, gluc: 58, lip: 19 },
  { id: "cornflakes", name: "Corn flakes", cat: "Féculents", kcal: 380, prot: 7, gluc: 84, lip: 1 },
  { id: "riz-souffle", name: "Céréales de riz soufflé", cat: "Féculents", kcal: 385, prot: 6, gluc: 88, lip: 1 },
  { id: "lentilles-cuites", name: "Lentilles cuites", cat: "Féculents", kcal: 116, prot: 9, gluc: 20, lip: 0.4 },
  { id: "pois-chiches", name: "Pois chiches cuits", cat: "Féculents", kcal: 164, prot: 8.9, gluc: 27, lip: 2.6 },
  { id: "haricots-rouges", name: "Haricots rouges cuits", cat: "Féculents", kcal: 127, prot: 8.7, gluc: 22, lip: 0.5 },
  { id: "haricots-blancs", name: "Haricots blancs cuits", cat: "Féculents", kcal: 120, prot: 8, gluc: 20, lip: 0.5 },
  { id: "petits-pois", name: "Petits pois", cat: "Féculents", kcal: 81, prot: 5.4, gluc: 12, lip: 0.4 },
  { id: "mais", name: "Maïs doux", cat: "Féculents", kcal: 96, prot: 3, gluc: 17, lip: 1.5 },

  /* ---------- Pains & viennoiseries ---------- */
  { id: "pain-blanc", name: "Baguette", cat: "Pains", kcal: 270, prot: 8.5, gluc: 55, lip: 1.5 },
  { id: "pain-complet", name: "Pain complet", cat: "Pains", kcal: 250, prot: 9, gluc: 45, lip: 3 },
  { id: "pain-cereales", name: "Pain aux céréales", cat: "Pains", kcal: 270, prot: 10, gluc: 45, lip: 5 },
  { id: "pain-seigle", name: "Pain de seigle", cat: "Pains", kcal: 240, prot: 7, gluc: 47, lip: 1.5 },
  { id: "pain-mie", name: "Pain de mie", cat: "Pains", kcal: 265, prot: 8, gluc: 48, lip: 4 },
  { id: "pain-mie-complet", name: "Pain de mie complet", cat: "Pains", kcal: 250, prot: 10, gluc: 42, lip: 4 },
  { id: "pain-pita", name: "Pain pita", cat: "Pains", kcal: 275, prot: 9, gluc: 55, lip: 1.5 },
  { id: "pain-burger", name: "Pain burger", cat: "Pains", kcal: 270, prot: 9, gluc: 48, lip: 5 },
  { id: "tortilla-wrap", name: "Tortilla / wrap (galette)", cat: "Pains", kcal: 310, prot: 8, gluc: 50, lip: 8 },
  { id: "bagel", name: "Bagel", cat: "Pains", kcal: 270, prot: 10, gluc: 50, lip: 2 },
  { id: "biscottes", name: "Biscottes", cat: "Pains", kcal: 405, prot: 11, gluc: 73, lip: 6 },
  { id: "galettes-riz", name: "Galettes de riz", cat: "Pains", kcal: 387, prot: 8, gluc: 82, lip: 2.8 },
  { id: "croissant", name: "Croissant", cat: "Pains", kcal: 406, prot: 8, gluc: 46, lip: 21 },
  { id: "pain-chocolat", name: "Pain au chocolat", cat: "Pains", kcal: 414, prot: 7.5, gluc: 44, lip: 23 },
  { id: "brioche", name: "Brioche", cat: "Pains", kcal: 375, prot: 8, gluc: 50, lip: 16 },
  { id: "pain-raisins", name: "Pain aux raisins", cat: "Pains", kcal: 335, prot: 7, gluc: 50, lip: 12 },

  /* ---------- Fruits ---------- */
  { id: "pomme", name: "Pomme", cat: "Fruits", kcal: 52, prot: 0.3, gluc: 14, lip: 0.2 },
  { id: "banane", name: "Banane", cat: "Fruits", kcal: 89, prot: 1.1, gluc: 23, lip: 0.3 },
  { id: "orange", name: "Orange", cat: "Fruits", kcal: 47, prot: 0.9, gluc: 12, lip: 0.1 },
  { id: "clementine", name: "Clémentine", cat: "Fruits", kcal: 47, prot: 0.8, gluc: 12, lip: 0.2 },
  { id: "poire", name: "Poire", cat: "Fruits", kcal: 57, prot: 0.4, gluc: 15, lip: 0.1 },
  { id: "peche", name: "Pêche", cat: "Fruits", kcal: 39, prot: 0.9, gluc: 10, lip: 0.3 },
  { id: "nectarine", name: "Nectarine", cat: "Fruits", kcal: 44, prot: 1.1, gluc: 11, lip: 0.3 },
  { id: "abricot", name: "Abricot", cat: "Fruits", kcal: 48, prot: 1.4, gluc: 11, lip: 0.4 },
  { id: "fraises", name: "Fraises", cat: "Fruits", kcal: 32, prot: 0.7, gluc: 8, lip: 0.3 },
  { id: "framboises", name: "Framboises", cat: "Fruits", kcal: 50, prot: 1.2, gluc: 11, lip: 0.6 },
  { id: "myrtilles", name: "Myrtilles", cat: "Fruits", kcal: 57, prot: 0.7, gluc: 14, lip: 0.3 },
  { id: "cerises", name: "Cerises", cat: "Fruits", kcal: 63, prot: 1.1, gluc: 16, lip: 0.2 },
  { id: "raisin", name: "Raisin", cat: "Fruits", kcal: 69, prot: 0.7, gluc: 18, lip: 0.2 },
  { id: "kiwi", name: "Kiwi", cat: "Fruits", kcal: 61, prot: 1.1, gluc: 15, lip: 0.5 },
  { id: "ananas", name: "Ananas", cat: "Fruits", kcal: 50, prot: 0.5, gluc: 13, lip: 0.1 },
  { id: "mangue", name: "Mangue", cat: "Fruits", kcal: 60, prot: 0.8, gluc: 15, lip: 0.4 },
  { id: "melon", name: "Melon", cat: "Fruits", kcal: 34, prot: 0.8, gluc: 8, lip: 0.2 },
  { id: "pasteque", name: "Pastèque", cat: "Fruits", kcal: 30, prot: 0.6, gluc: 8, lip: 0.2 },
  { id: "citron", name: "Citron", cat: "Fruits", kcal: 29, prot: 1.1, gluc: 9, lip: 0.3 },
  { id: "pamplemousse", name: "Pamplemousse", cat: "Fruits", kcal: 42, prot: 0.8, gluc: 11, lip: 0.1 },
  { id: "grenade", name: "Grenade", cat: "Fruits", kcal: 83, prot: 1.7, gluc: 19, lip: 1.2 },
  { id: "figue", name: "Figue fraîche", cat: "Fruits", kcal: 74, prot: 0.8, gluc: 19, lip: 0.3 },
  { id: "prune", name: "Prune", cat: "Fruits", kcal: 46, prot: 0.7, gluc: 11, lip: 0.3 },
  { id: "litchi", name: "Litchi", cat: "Fruits", kcal: 66, prot: 0.8, gluc: 17, lip: 0.4 },
  { id: "fruit-passion", name: "Fruit de la passion", cat: "Fruits", kcal: 97, prot: 2.2, gluc: 23, lip: 0.7 },
  { id: "datte", name: "Dattes", cat: "Fruits", kcal: 282, prot: 2.5, gluc: 75, lip: 0.4 },
  { id: "figues-seches", name: "Figues sèches", cat: "Fruits", kcal: 250, prot: 3.3, gluc: 64, lip: 0.9 },
  { id: "abricots-secs", name: "Abricots secs", cat: "Fruits", kcal: 240, prot: 3.4, gluc: 63, lip: 0.5 },
  { id: "raisins-secs", name: "Raisins secs", cat: "Fruits", kcal: 300, prot: 3, gluc: 79, lip: 0.5 },
  { id: "pruneaux", name: "Pruneaux", cat: "Fruits", kcal: 240, prot: 2.2, gluc: 64, lip: 0.4 },
  { id: "compote", name: "Compote de pommes", cat: "Fruits", kcal: 90, prot: 0.3, gluc: 21, lip: 0.2 },
  { id: "compote-ss", name: "Compote sans sucre ajouté", cat: "Fruits", kcal: 60, prot: 0.3, gluc: 14, lip: 0.2 },

  /* ---------- Légumes ---------- */
  { id: "brocoli", name: "Brocoli", cat: "Légumes", kcal: 34, prot: 2.8, gluc: 7, lip: 0.4 },
  { id: "haricots-verts", name: "Haricots verts", cat: "Légumes", kcal: 31, prot: 1.8, gluc: 7, lip: 0.1 },
  { id: "epinards", name: "Épinards", cat: "Légumes", kcal: 23, prot: 2.9, gluc: 3.6, lip: 0.4 },
  { id: "tomate", name: "Tomate", cat: "Légumes", kcal: 18, prot: 0.9, gluc: 3.9, lip: 0.2 },
  { id: "tomates-cerises", name: "Tomates cerises", cat: "Légumes", kcal: 20, prot: 1, gluc: 4, lip: 0.2 },
  { id: "carotte", name: "Carotte", cat: "Légumes", kcal: 41, prot: 0.9, gluc: 10, lip: 0.2 },
  { id: "courgette", name: "Courgette", cat: "Légumes", kcal: 17, prot: 1.2, gluc: 3.1, lip: 0.3 },
  { id: "concombre", name: "Concombre", cat: "Légumes", kcal: 15, prot: 0.7, gluc: 3.6, lip: 0.1 },
  { id: "poivron", name: "Poivron", cat: "Légumes", kcal: 26, prot: 1, gluc: 6, lip: 0.3 },
  { id: "aubergine", name: "Aubergine", cat: "Légumes", kcal: 25, prot: 1, gluc: 6, lip: 0.2 },
  { id: "champignons", name: "Champignons de Paris", cat: "Légumes", kcal: 22, prot: 3.1, gluc: 3.3, lip: 0.3 },
  { id: "salade", name: "Salade verte", cat: "Légumes", kcal: 15, prot: 1.4, gluc: 2.9, lip: 0.2 },
  { id: "chou-fleur", name: "Chou-fleur", cat: "Légumes", kcal: 25, prot: 1.9, gluc: 5, lip: 0.3 },
  { id: "choux-bruxelles", name: "Choux de Bruxelles", cat: "Légumes", kcal: 43, prot: 3.4, gluc: 9, lip: 0.3 },
  { id: "chou-rouge", name: "Chou rouge", cat: "Légumes", kcal: 31, prot: 1.4, gluc: 7, lip: 0.2 },
  { id: "asperges", name: "Asperges", cat: "Légumes", kcal: 20, prot: 2.2, gluc: 3.9, lip: 0.1 },
  { id: "poireau", name: "Poireau", cat: "Légumes", kcal: 30, prot: 1.5, gluc: 6, lip: 0.3 },
  { id: "artichaut", name: "Artichaut", cat: "Légumes", kcal: 47, prot: 3.3, gluc: 11, lip: 0.2 },
  { id: "betterave", name: "Betterave", cat: "Légumes", kcal: 43, prot: 1.6, gluc: 10, lip: 0.2 },
  { id: "radis", name: "Radis", cat: "Légumes", kcal: 16, prot: 0.7, gluc: 3.4, lip: 0.1 },
  { id: "oignon", name: "Oignon", cat: "Légumes", kcal: 40, prot: 1.1, gluc: 9, lip: 0.1 },
  { id: "ail", name: "Ail", cat: "Légumes", kcal: 131, prot: 6, gluc: 28, lip: 0.5 },
  { id: "avocat", name: "Avocat", cat: "Légumes", kcal: 160, prot: 2, gluc: 9, lip: 15 },
  { id: "potiron", name: "Potiron / courge", cat: "Légumes", kcal: 26, prot: 1, gluc: 6.5, lip: 0.1 },
  { id: "endive", name: "Endive", cat: "Légumes", kcal: 17, prot: 0.9, gluc: 3, lip: 0.1 },
  { id: "fenouil", name: "Fenouil", cat: "Légumes", kcal: 31, prot: 1.2, gluc: 7, lip: 0.2 },
  { id: "celeri", name: "Céleri branche", cat: "Légumes", kcal: 16, prot: 0.7, gluc: 3, lip: 0.2 },
  { id: "edamame", name: "Edamame", cat: "Légumes", kcal: 122, prot: 11, gluc: 9, lip: 5 },
  { id: "ratatouille", name: "Ratatouille", cat: "Légumes", kcal: 55, prot: 1.3, gluc: 6, lip: 3 },

  /* ---------- Produits laitiers ---------- */
  { id: "lait-ecreme", name: "Lait écrémé", cat: "Produits laitiers", kcal: 33, prot: 3.3, gluc: 4.9, lip: 0.1 },
  { id: "lait-demi", name: "Lait demi-écrémé", cat: "Produits laitiers", kcal: 46, prot: 3.2, gluc: 4.8, lip: 1.6 },
  { id: "lait-entier", name: "Lait entier", cat: "Produits laitiers", kcal: 63, prot: 3.2, gluc: 4.7, lip: 3.6 },
  { id: "lait-amande", name: "Lait d'amande", cat: "Produits laitiers", kcal: 24, prot: 0.5, gluc: 3, lip: 1.1 },
  { id: "lait-soja", name: "Lait de soja", cat: "Produits laitiers", kcal: 40, prot: 3.7, gluc: 2, lip: 1.9 },
  { id: "lait-avoine", name: "Lait d'avoine", cat: "Produits laitiers", kcal: 45, prot: 1, gluc: 7, lip: 1.5 },
  { id: "yaourt-nature", name: "Yaourt nature", cat: "Produits laitiers", kcal: 58, prot: 4, gluc: 4.7, lip: 3 },
  { id: "yaourt-grec", name: "Yaourt grec", cat: "Produits laitiers", kcal: 97, prot: 9, gluc: 3.5, lip: 5 },
  { id: "yaourt-fruits", name: "Yaourt aux fruits", cat: "Produits laitiers", kcal: 95, prot: 3.5, gluc: 14, lip: 2.5 },
  { id: "skyr", name: "Skyr", cat: "Produits laitiers", kcal: 57, prot: 10, gluc: 4, lip: 0.2 },
  { id: "fromage-blanc-0", name: "Fromage blanc 0%", cat: "Produits laitiers", kcal: 47, prot: 8, gluc: 4, lip: 0.2 },
  { id: "fromage-blanc-3", name: "Fromage blanc 3%", cat: "Produits laitiers", kcal: 72, prot: 7, gluc: 4, lip: 3 },
  { id: "petit-suisse", name: "Petit-suisse nature", cat: "Produits laitiers", kcal: 116, prot: 9.5, gluc: 3.5, lip: 7 },
  { id: "creme-fraiche", name: "Crème fraîche 30%", cat: "Produits laitiers", kcal: 300, prot: 2.3, gluc: 3, lip: 30 },
  { id: "creme-legere", name: "Crème fraîche légère 15%", cat: "Produits laitiers", kcal: 165, prot: 2.5, gluc: 4, lip: 15 },

  /* ---------- Fromages ---------- */
  { id: "emmental", name: "Emmental", cat: "Fromages", kcal: 380, prot: 28, gluc: 0.5, lip: 29 },
  { id: "comte", name: "Comté", cat: "Fromages", kcal: 410, prot: 26.5, gluc: 0, lip: 34 },
  { id: "gruyere-rape", name: "Fromage râpé", cat: "Fromages", kcal: 400, prot: 27, gluc: 0.5, lip: 32 },
  { id: "camembert", name: "Camembert", cat: "Fromages", kcal: 265, prot: 20, gluc: 0.5, lip: 21 },
  { id: "brie", name: "Brie", cat: "Fromages", kcal: 334, prot: 20, gluc: 0.5, lip: 28 },
  { id: "chevre", name: "Fromage de chèvre (bûche)", cat: "Fromages", kcal: 290, prot: 19, gluc: 2, lip: 23 },
  { id: "feta", name: "Feta", cat: "Fromages", kcal: 264, prot: 14, gluc: 4, lip: 21 },
  { id: "mozzarella", name: "Mozzarella", cat: "Fromages", kcal: 280, prot: 18, gluc: 2, lip: 22 },
  { id: "parmesan", name: "Parmesan", cat: "Fromages", kcal: 400, prot: 36, gluc: 0.5, lip: 28 },
  { id: "roquefort", name: "Roquefort", cat: "Fromages", kcal: 369, prot: 19, gluc: 2, lip: 32 },
  { id: "reblochon", name: "Reblochon", cat: "Fromages", kcal: 330, prot: 20, gluc: 0.5, lip: 28 },
  { id: "raclette", name: "Fromage à raclette", cat: "Fromages", kcal: 360, prot: 23, gluc: 0.5, lip: 30 },
  { id: "cheddar", name: "Cheddar", cat: "Fromages", kcal: 410, prot: 25, gluc: 1, lip: 33 },
  { id: "boursin", name: "Fromage frais ail & fines herbes", cat: "Fromages", kcal: 405, prot: 7, gluc: 3, lip: 40 },
  { id: "st-moret", name: "Fromage frais à tartiner", cat: "Fromages", kcal: 195, prot: 7, gluc: 3, lip: 17 },
  { id: "kiri", name: "Fromage fondu (type Kiri)", cat: "Fromages", kcal: 310, prot: 8, gluc: 3, lip: 29 },
  { id: "babybel", name: "Mini fromage (type Babybel)", cat: "Fromages", kcal: 300, prot: 22, gluc: 0, lip: 23 },
  { id: "cancoillotte", name: "Cancoillotte", cat: "Fromages", kcal: 120, prot: 15, gluc: 1, lip: 5 },

  /* ---------- Noix & graines ---------- */
  { id: "amandes", name: "Amandes", cat: "Noix & graines", kcal: 620, prot: 21, gluc: 8, lip: 53 },
  { id: "noix", name: "Noix", cat: "Noix & graines", kcal: 690, prot: 15, gluc: 11, lip: 66 },
  { id: "noix-cajou", name: "Noix de cajou", cat: "Noix & graines", kcal: 580, prot: 18, gluc: 27, lip: 45 },
  { id: "noisettes", name: "Noisettes", cat: "Noix & graines", kcal: 640, prot: 15, gluc: 10, lip: 61 },
  { id: "pistaches", name: "Pistaches", cat: "Noix & graines", kcal: 570, prot: 21, gluc: 17, lip: 46 },
  { id: "cacahuetes", name: "Cacahuètes", cat: "Noix & graines", kcal: 600, prot: 26, gluc: 12, lip: 50 },
  { id: "beurre-cacahuete", name: "Beurre de cacahuète", cat: "Noix & graines", kcal: 600, prot: 25, gluc: 14, lip: 50 },
  { id: "beurre-amande", name: "Purée d'amande", cat: "Noix & graines", kcal: 620, prot: 21, gluc: 9, lip: 55 },
  { id: "graines-chia", name: "Graines de chia", cat: "Noix & graines", kcal: 480, prot: 17, gluc: 8, lip: 31 },
  { id: "graines-lin", name: "Graines de lin", cat: "Noix & graines", kcal: 510, prot: 18, gluc: 1, lip: 42 },
  { id: "graines-tournesol", name: "Graines de tournesol", cat: "Noix & graines", kcal: 580, prot: 21, gluc: 11, lip: 49 },
  { id: "graines-courge", name: "Graines de courge", cat: "Noix & graines", kcal: 560, prot: 25, gluc: 11, lip: 46 },
  { id: "coco-rape", name: "Noix de coco râpée", cat: "Noix & graines", kcal: 660, prot: 6, gluc: 8, lip: 64 },

  /* ---------- Sucré & snacks ---------- */
  { id: "chocolat-noir", name: "Chocolat noir 70%", cat: "Sucré & snacks", kcal: 570, prot: 8, gluc: 34, lip: 42 },
  { id: "chocolat-lait", name: "Chocolat au lait", cat: "Sucré & snacks", kcal: 535, prot: 7, gluc: 57, lip: 30 },
  { id: "chocolat-blanc", name: "Chocolat blanc", cat: "Sucré & snacks", kcal: 539, prot: 6, gluc: 59, lip: 31 },
  { id: "pate-tartiner", name: "Pâte à tartiner (type Nutella)", cat: "Sucré & snacks", kcal: 539, prot: 6, gluc: 57, lip: 31 },
  { id: "confiture", name: "Confiture", cat: "Sucré & snacks", kcal: 240, prot: 0.4, gluc: 60, lip: 0.1 },
  { id: "miel", name: "Miel", cat: "Sucré & snacks", kcal: 304, prot: 0.3, gluc: 82, lip: 0 },
  { id: "sucre", name: "Sucre", cat: "Sucré & snacks", kcal: 400, prot: 0, gluc: 100, lip: 0 },
  { id: "petit-beurre", name: "Biscuits petit-beurre", cat: "Sucré & snacks", kcal: 435, prot: 7, gluc: 74, lip: 12 },
  { id: "cookies", name: "Cookies", cat: "Sucré & snacks", kcal: 480, prot: 5, gluc: 64, lip: 22 },
  { id: "madeleine", name: "Madeleines", cat: "Sucré & snacks", kcal: 450, prot: 6, gluc: 52, lip: 24 },
  { id: "brownie", name: "Brownie / gâteau chocolat", cat: "Sucré & snacks", kcal: 430, prot: 5, gluc: 50, lip: 22 },
  { id: "muffin", name: "Muffin au chocolat", cat: "Sucré & snacks", kcal: 420, prot: 5, gluc: 50, lip: 22 },
  { id: "donut", name: "Donut", cat: "Sucré & snacks", kcal: 425, prot: 5, gluc: 50, lip: 22 },
  { id: "gaufre", name: "Gaufre", cat: "Sucré & snacks", kcal: 330, prot: 7, gluc: 45, lip: 14 },
  { id: "crepe", name: "Crêpe sucrée", cat: "Sucré & snacks", kcal: 190, prot: 5, gluc: 28, lip: 7 },
  { id: "pancake", name: "Pancakes", cat: "Sucré & snacks", kcal: 230, prot: 6, gluc: 30, lip: 9 },
  { id: "tarte-pommes", name: "Tarte aux pommes", cat: "Sucré & snacks", kcal: 250, prot: 2.5, gluc: 35, lip: 11 },
  { id: "pain-epices", name: "Pain d'épices", cat: "Sucré & snacks", kcal: 350, prot: 4, gluc: 75, lip: 3 },
  { id: "glace-vanille", name: "Glace vanille", cat: "Sucré & snacks", kcal: 200, prot: 3.5, gluc: 24, lip: 10 },
  { id: "sorbet", name: "Sorbet", cat: "Sucré & snacks", kcal: 130, prot: 0.5, gluc: 32, lip: 0 },
  { id: "mousse-chocolat", name: "Mousse au chocolat", cat: "Sucré & snacks", kcal: 220, prot: 5, gluc: 26, lip: 11 },
  { id: "creme-dessert", name: "Crème dessert chocolat", cat: "Sucré & snacks", kcal: 122, prot: 3.5, gluc: 19, lip: 4 },
  { id: "riz-au-lait", name: "Riz au lait", cat: "Sucré & snacks", kcal: 120, prot: 3.5, gluc: 20, lip: 3 },
  { id: "flan", name: "Flan pâtissier", cat: "Sucré & snacks", kcal: 190, prot: 4.5, gluc: 28, lip: 7 },
  { id: "bonbons", name: "Bonbons gélifiés", cat: "Sucré & snacks", kcal: 350, prot: 5, gluc: 80, lip: 0 },
  { id: "barre-cereales", name: "Barre de céréales", cat: "Sucré & snacks", kcal: 400, prot: 6, gluc: 65, lip: 12 },
  { id: "barre-chocolatee", name: "Barre chocolatée (type Snickers)", cat: "Sucré & snacks", kcal: 485, prot: 8, gluc: 56, lip: 24 },
  { id: "chips", name: "Chips", cat: "Sucré & snacks", kcal: 530, prot: 6, gluc: 50, lip: 33 },
  { id: "chips-tortilla", name: "Chips tortilla", cat: "Sucré & snacks", kcal: 495, prot: 7, gluc: 60, lip: 24 },
  { id: "popcorn", name: "Popcorn sucré", cat: "Sucré & snacks", kcal: 430, prot: 7, gluc: 72, lip: 12 },
  { id: "crackers", name: "Crackers apéritif", cat: "Sucré & snacks", kcal: 460, prot: 9, gluc: 60, lip: 20 },
  { id: "olives", name: "Olives", cat: "Sucré & snacks", kcal: 145, prot: 1, gluc: 4, lip: 14 },

  /* ---------- Boissons (pour 100 ml) ---------- */
  { id: "jus-orange", name: "Jus d'orange", cat: "Boissons", kcal: 45, prot: 0.7, gluc: 10, lip: 0.2 },
  { id: "jus-pomme", name: "Jus de pomme", cat: "Boissons", kcal: 44, prot: 0.1, gluc: 11, lip: 0.1 },
  { id: "jus-multifruits", name: "Jus multifruits", cat: "Boissons", kcal: 50, prot: 0.4, gluc: 12, lip: 0.1 },
  { id: "smoothie", name: "Smoothie", cat: "Boissons", kcal: 55, prot: 0.6, gluc: 12, lip: 0.3 },
  { id: "coca", name: "Soda cola", cat: "Boissons", kcal: 42, prot: 0, gluc: 10.6, lip: 0 },
  { id: "coca-zero", name: "Soda cola zéro", cat: "Boissons", kcal: 0, prot: 0, gluc: 0, lip: 0 },
  { id: "limonade", name: "Limonade", cat: "Boissons", kcal: 40, prot: 0, gluc: 10, lip: 0 },
  { id: "ice-tea", name: "Thé glacé sucré", cat: "Boissons", kcal: 30, prot: 0, gluc: 7, lip: 0 },
  { id: "boisson-energisante", name: "Boisson énergisante", cat: "Boissons", kcal: 45, prot: 0, gluc: 11, lip: 0 },
  { id: "boisson-isotonique", name: "Boisson isotonique", cat: "Boissons", kcal: 26, prot: 0, gluc: 6, lip: 0 },
  { id: "cafe", name: "Café noir", cat: "Boissons", kcal: 2, prot: 0.1, gluc: 0.3, lip: 0 },
  { id: "the", name: "Thé non sucré", cat: "Boissons", kcal: 1, prot: 0, gluc: 0.2, lip: 0 },
  { id: "chocolat-chaud", name: "Chocolat chaud", cat: "Boissons", kcal: 89, prot: 3.5, gluc: 10, lip: 3 },
  { id: "biere", name: "Bière blonde (5°)", cat: "Boissons", kcal: 43, prot: 0.5, gluc: 3.5, lip: 0 },
  { id: "vin-rouge", name: "Vin rouge (12°)", cat: "Boissons", kcal: 83, prot: 0.1, gluc: 2.6, lip: 0 },
  { id: "vin-blanc", name: "Vin blanc sec", cat: "Boissons", kcal: 77, prot: 0.1, gluc: 1, lip: 0 },
  { id: "champagne", name: "Champagne", cat: "Boissons", kcal: 76, prot: 0.3, gluc: 1.4, lip: 0 },
  { id: "spiritueux", name: "Spiritueux (40°)", cat: "Boissons", kcal: 235, prot: 0, gluc: 0, lip: 0 },

  /* ---------- Sauces & matières grasses ---------- */
  { id: "huile-olive", name: "Huile d'olive", cat: "Sauces & MG", kcal: 900, prot: 0, gluc: 0, lip: 100 },
  { id: "huile-colza", name: "Huile de colza", cat: "Sauces & MG", kcal: 900, prot: 0, gluc: 0, lip: 100 },
  { id: "huile-coco", name: "Huile de coco", cat: "Sauces & MG", kcal: 900, prot: 0, gluc: 0, lip: 100 },
  { id: "beurre", name: "Beurre", cat: "Sauces & MG", kcal: 745, prot: 0.7, gluc: 0.6, lip: 82 },
  { id: "beurre-allege", name: "Beurre allégé 41%", cat: "Sauces & MG", kcal: 380, prot: 0.5, gluc: 0.5, lip: 41 },
  { id: "margarine", name: "Margarine", cat: "Sauces & MG", kcal: 540, prot: 0, gluc: 0, lip: 60 },
  { id: "mayonnaise", name: "Mayonnaise", cat: "Sauces & MG", kcal: 700, prot: 1, gluc: 3, lip: 75 },
  { id: "ketchup", name: "Ketchup", cat: "Sauces & MG", kcal: 102, prot: 1.2, gluc: 23, lip: 0.2 },
  { id: "moutarde", name: "Moutarde", cat: "Sauces & MG", kcal: 150, prot: 7, gluc: 5, lip: 11 },
  { id: "sauce-tomate", name: "Sauce tomate cuisinée", cat: "Sauces & MG", kcal: 60, prot: 1.4, gluc: 7, lip: 2.3 },
  { id: "pesto", name: "Pesto", cat: "Sauces & MG", kcal: 460, prot: 5, gluc: 8, lip: 44 },
  { id: "sauce-soja", name: "Sauce soja", cat: "Sauces & MG", kcal: 53, prot: 6, gluc: 6, lip: 0 },
  { id: "vinaigrette", name: "Vinaigrette", cat: "Sauces & MG", kcal: 400, prot: 0.5, gluc: 4, lip: 40 },
  { id: "sauce-bbq", name: "Sauce barbecue", cat: "Sauces & MG", kcal: 130, prot: 1, gluc: 30, lip: 0.5 },
  { id: "sauce-bearnaise", name: "Sauce béarnaise", cat: "Sauces & MG", kcal: 550, prot: 1.5, gluc: 3, lip: 58 },
  { id: "guacamole", name: "Guacamole", cat: "Sauces & MG", kcal: 150, prot: 2, gluc: 6, lip: 13 },
  { id: "houmous", name: "Houmous", cat: "Sauces & MG", kcal: 240, prot: 7, gluc: 12, lip: 18 },
  { id: "tapenade", name: "Tapenade", cat: "Sauces & MG", kcal: 250, prot: 2.5, gluc: 4, lip: 25 },

  /* ---------- Plats & fast-food ---------- */
  { id: "pizza-margherita", name: "Pizza margherita", cat: "Plats & fast-food", kcal: 240, prot: 10, gluc: 28, lip: 9 },
  { id: "pizza-fromages", name: "Pizza 4 fromages", cat: "Plats & fast-food", kcal: 270, prot: 12, gluc: 26, lip: 13 },
  { id: "cheeseburger", name: "Cheeseburger", cat: "Plats & fast-food", kcal: 263, prot: 13, gluc: 30, lip: 11 },
  { id: "burger-double", name: "Burger double (type Big Mac)", cat: "Plats & fast-food", kcal: 230, prot: 12, gluc: 18, lip: 12 },
  { id: "kebab", name: "Kebab (sandwich)", cat: "Plats & fast-food", kcal: 220, prot: 12, gluc: 20, lip: 10 },
  { id: "nuggets", name: "Nuggets de poulet", cat: "Plats & fast-food", kcal: 255, prot: 14, gluc: 16, lip: 15 },
  { id: "hot-dog", name: "Hot-dog", cat: "Plats & fast-food", kcal: 250, prot: 10, gluc: 25, lip: 12 },
  { id: "sandwich-jambon", name: "Sandwich jambon-beurre", cat: "Plats & fast-food", kcal: 265, prot: 10, gluc: 32, lip: 10 },
  { id: "wrap-poulet", name: "Wrap au poulet", cat: "Plats & fast-food", kcal: 200, prot: 10, gluc: 22, lip: 8 },
  { id: "croque-monsieur", name: "Croque-monsieur", cat: "Plats & fast-food", kcal: 280, prot: 14, gluc: 25, lip: 14 },
  { id: "quiche-lorraine", name: "Quiche lorraine", cat: "Plats & fast-food", kcal: 280, prot: 9, gluc: 22, lip: 17 },
  { id: "cordon-bleu", name: "Cordon bleu", cat: "Plats & fast-food", kcal: 245, prot: 15, gluc: 13, lip: 15 },
  { id: "lasagnes", name: "Lasagnes bolognaise", cat: "Plats & fast-food", kcal: 150, prot: 8, gluc: 14, lip: 6 },
  { id: "hachis", name: "Hachis parmentier", cat: "Plats & fast-food", kcal: 115, prot: 7, gluc: 11, lip: 5 },
  { id: "pates-carbonara", name: "Pâtes à la carbonara", cat: "Plats & fast-food", kcal: 160, prot: 7, gluc: 18, lip: 7 },
  { id: "pates-bolognaise", name: "Pâtes à la bolognaise", cat: "Plats & fast-food", kcal: 130, prot: 6, gluc: 17, lip: 4 },
  { id: "couscous", name: "Couscous (plat complet)", cat: "Plats & fast-food", kcal: 145, prot: 8, gluc: 17, lip: 5 },
  { id: "paella", name: "Paella", cat: "Plats & fast-food", kcal: 155, prot: 8, gluc: 18, lip: 5 },
  { id: "riz-cantonais", name: "Riz cantonais", cat: "Plats & fast-food", kcal: 160, prot: 6, gluc: 23, lip: 5 },
  { id: "sushi", name: "Sushis (saumon)", cat: "Plats & fast-food", kcal: 145, prot: 6, gluc: 25, lip: 2.5 },
  { id: "nouilles-instant", name: "Nouilles instantanées (préparées)", cat: "Plats & fast-food", kcal: 135, prot: 3, gluc: 18, lip: 6 },
  { id: "taboule", name: "Taboulé", cat: "Plats & fast-food", kcal: 145, prot: 4, gluc: 22, lip: 4 },
  { id: "salade-cesar", name: "Salade César", cat: "Plats & fast-food", kcal: 180, prot: 8, gluc: 8, lip: 13 },
  { id: "soupe-legumes", name: "Soupe de légumes", cat: "Plats & fast-food", kcal: 33, prot: 1, gluc: 5, lip: 1 },
  { id: "ravioli-boite", name: "Raviolis sauce tomate (boîte)", cat: "Plats & fast-food", kcal: 90, prot: 3.5, gluc: 13, lip: 2.5 },
  { id: "chili", name: "Chili con carne", cat: "Plats & fast-food", kcal: 120, prot: 8, gluc: 10, lip: 5 },
  { id: "boeuf-bourguignon", name: "Bœuf bourguignon", cat: "Plats & fast-food", kcal: 115, prot: 11, gluc: 4, lip: 6 },
  { id: "blanquette", name: "Blanquette de veau", cat: "Plats & fast-food", kcal: 120, prot: 9, gluc: 6, lip: 7 },
  { id: "gratin-dauphinois", name: "Gratin dauphinois", cat: "Plats & fast-food", kcal: 130, prot: 3, gluc: 13, lip: 7 },

  /* ---------- Compléments sportifs ---------- */
  { id: "whey", name: "Whey protéine", cat: "Compléments", kcal: 390, prot: 78, gluc: 6, lip: 6 },
  { id: "caseine", name: "Caséine", cat: "Compléments", kcal: 370, prot: 75, gluc: 8, lip: 2 },
  { id: "gainer", name: "Gainer", cat: "Compléments", kcal: 390, prot: 25, gluc: 60, lip: 5 },
  { id: "barre-proteinee", name: "Barre protéinée", cat: "Compléments", kcal: 380, prot: 33, gluc: 35, lip: 12 },
];

export const FOOD_CATEGORIES = [
  "Viandes", "Poissons & mer", "Œufs & végétal", "Féculents", "Pains",
  "Fruits", "Légumes", "Produits laitiers", "Fromages", "Noix & graines",
  "Sucré & snacks", "Boissons", "Sauces & MG", "Plats & fast-food", "Compléments",
];

export const MEALS = [
  { id: "breakfast", name: "Petit-déjeuner", icon: "🌅" },
  { id: "lunch", name: "Déjeuner", icon: "☀️" },
  { id: "dinner", name: "Dîner", icon: "🌙" },
  { id: "snack", name: "Collations", icon: "🍎" },
];
